words:
  - chala
  - bagundi
  - undi
  - ledu
  - inka
  - kani
  - aithe
  - nenu
  - meeru
  - mana
  - vellanu
  - chesanu
  - chesadu
  - vastundi
  - tho
  - ki
  - lo
  - ra
  - amma
  - anna
  - mowa
  - asalu
  - koncham
  - ayyaka
  - chestha
  - champestunnaru
  - velthunnava
  - eppudu
  - ela
  - ekkada
  - enduku
  - evaru
  - avunu
  - kadu
  - kachitamga
  - pakka
  - idhi
  - adhi
  - e
  - aa
  - ani
  - em
  - emi
  - enti
  - emiti
  - mari
  - kada
  - antu
  - tharvatha
  - mundu
  - pyna
  - kinda
  - lopal
  - bayata
  - eroju
  - repu
  - ninna
  - roju
  - poyina
  - vachina
  - baga
  - super
  - Peaks
  - peaks
  - racha
  - keka
  - aipoindo
  - teliyaledu
  - vastunnayi
  - sacha
  - navvaleka
  - chusi
  - emundi
  - cheyyi
