suffixes:
  - adu
  - indi
  - anu
  - unnadu
  - unnaru
  - tha
  - thunnanu
  - thunnaru
  - thundi
  - tho
  - ki
  - lo
  - ni
  - ani
  - amma
  - anna
  - ledu
  - ledha
  - avva
  - ayya
  - undi
  - inka
  - ga
  - nna
  - rru
  - vi
  - vu
  - va
  - vva
  - le
  - vi
  - lu
